9-6. 학생 본인인증 실패 시, 오류 사유 log로 print 되도록 수정
DA-sc21/test-helper-ai pull request #2
Opened 2021-10-30 12:36 UTC by KoYeJoon

🧸branch
- dev ← feature

📌 기능
- 1차 학생 본인인증 실패 시 오류 사유 log로 프린트되도록 수정

✔️ 확인해야 할 사항
- @WooNaYoung22 @leeshyeon  구현하면서 학생 본인인증 실패 시, log로 오류 이유 뜨게 했으니 참고하면서 개발하세요 :)

✏️ 추후 변경될 수 있는 사항
- X

2021-11-01 16:56 UTC, KoYeJoon commented
test code로 시험해본 뒤 다시 열기

2021-11-03 07:57 UTC, jmchoi1225 requested changes
수고하셨습니다!
- AI/src/student_identification/detectText.py에서 sys.stderr.write가 없는 것이 맞나요?

2021-11-03 11:44 UTC, KoYeJoon commented
> 수고하셨습니다!
> 
> * AI/src/student_identification/detectText.py에서 sys.stderr.write가 없는 것이 맞나요?

이게 같은 feature로 여러 개의 브랜치가 있다보니 엄청 헷깔리네요 ! 수정해서 다시 올리겠습니다 :)

2021-11-04 09:57 UTC, jmchoi1225 approved these changes
수고하셨습니다!

2021-11-04 11:45 UTC, merged